name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - uses: docker/build-push-action@master
        with:
          context: .
          push: true
          tags: pabpereza/pabpereza:latestk
  deploy:
    name: Deploy on linux ssh server 
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull pabpereza/pabpereza:latest
          docker rm -f pabpereza || true
          docker run -d pabpereza/pabpereza:latest
